# _config.yml

theme: jekyll-theme-primer
remote_theme: pages-themes/cayman@v0.2.0
name: HR Interview Questions for Developers
title: null
description: A community-built cheatsheet with answers to common HR questions for developer interviews.
