# _config.yml

theme: jekyll-theme-primer
remote_theme: pages-themes/cayman@v0.2.0
name: HR Interview Questions for Developers
title: null
description: An open-source guide to help you with the HR questions in your next developer interview.
